version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    user: root
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/data
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    network_mode: "host"


      # networks:
#   default:
#     external:
#       name: host
      #     networks:
#         - public
# # networks:
# #     dockernet:
# #         external: true